version: '3.3'

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: start
    volumes:
      - .:/app/
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - api

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=smartback
      - POSTGRES_USER=smartback
      - POSTGRES_PASSWORD=smartback

volumes:
  pgdata:

networks:
  default:
    external:
      name: shared-network-smartback